name: quanht_dropdown_custom
description: " A dropdown component that automatically enables scroll-down functionality when the total height of the dropdown content exceeds the visible or defined space"
version: 0.0.3
homepage: "https://github.com/trungquan2k/quanht_dropdown_custom"

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

assets:
  - assets/images/
